chore: remove husky to build

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,9 +1,9 @@
-#!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
+# #!/bin/sh
+# . "$(dirname "$0")/_/husky.sh"
 
-branch="$(git rev-parse --abbrev-ref HEAD)"
+# branch="$(git rev-parse --abbrev-ref HEAD)"
 
-if [ "$branch" = "main" ]; then
-  echo "You can't push directly to main branch"
-  exit 1
-fi
+# if [ "$branch" = "main" ]; then
+#   echo "You can't push directly to main branch"
+#   exit 1
+# fi
